language: clojure
jdk:
  - oraclejdk8

# Environment variables (e.g. encrypted credentials).
# env:
#   global:
#   - var1
#   - var2

# stages:
# - test
# - publish

# Pipeline stages.
jobs:
  include:
  - stage: test
    if: branch IN (master, devel) OR branch =~ ^version-
    script:
    - export INGEST_VERSION=$(lein pom &> /dev/null && mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)
    - echo "I'm testing Ingestor "$INGEST_VERSION
  # - stage: publish
  #   if: branch IN (master, devel) OR branch =~ ^version-
  #   script:
  #   - echo "I'm publishing..."
