# Dummy
language: clojure
jdk:
  - oraclejdk8

env:
  global:
    - secure: l+V5hNyahNz2BhMcXy4k6fcCo4sTIgT2jlvAA5qLbcgrfcDKfHJAs55uSiOfQf30aW7KOU5PA3dAwjFGwLMAO6DNdHTUWpO5dQl7zOdWhg3i0ADHPlMaNWPsaS6Ff3QII5FdGpd6u1RAjJoeD1UJZvKRZAqTozNPY5nwmAlYlZx+HA6IRMInAE7uJCmZq/S5L8dFOziP3VTLdfJjTxHBouJKs7VWnW2zFDd5Wl0LDAaZv9rwLra2wbemgfmNyh3q7e31q7ZH1g9tr+loTsnXTR3EN43HiUcW/KWBbDq3WWhqRKo8n0YyT1W+/9+2cFdVxcx1nMdgbEw+HFVfijQMivRXyD19bFYMBIk3QaLif2Iig1IhEAmDtoul4DbTe1pqQufWLyljCQ1vzhA3x6lNpAhTU0HKZqXdbWnY8jSHlfqeCrCpnYgNgA3IzPNkkYbSaQuGJpsdzfF4ZUyKK82d9KvXgBfdsbQ1FlH0dsbh+JQ7VlfZYIoQz8yxQSWF2aB22oS6pb6Td4ikcuzvP1asFxB6g0NbD4jwRsdMQItWRWUxzDfpCiu8Pi7A5v/5h2vvN6mWBKMOYxjdplkT21IsvboODbYAyrP2nKettzeywgoyHOI7I0eLFTQ7btKxOXfL+lb/ssUB52pAQv4NcbTVuYq16u39DvoPQu4SYnonlWM=
    - secure: TRegnySfji1i2qHyugoIIuKW4BcELE6jKAe7R4yX5UY0ti/igBQppR2ZAolP7lmLobjYqDDBg4jhCd9REXxNokyXVpEc0fpG0EO5oHk492QmbTRFXgL8Dk6Rjuz9iI5e+itYLvUBHgEejtyXnofCRCcGcO0AJRotWSfdeEhlpRPB9x5U1Gl6hYkHtNf7Bfp4eN7BXl9IzN+993ft8bT5ItjVh010ygUYLmhn+yq/T9tJRgL+zLhGJB/eofbkb2VA5u8l7bKV6GjBJvsLZcuXtWgVpMNQBNWnmhxINAtfExFa4V2a+IYGdYtG/u26EVaNk0YHhwu8OUo4M8Wc3iGNLJVInjMVvIm6a7A1egp+SH7TMIgRihsRwhPWSZRiKrxs2N1C/U70ghAjWT4M5mcNK5KD50SRc7ogUxcjtPUQzQqbAm9HOyWsQv2ZlPo4XOdBbZAxZpV8EHB0mzfuNdDnlYvmpFgJnATYmYtTexMbIUzMB+KwyiPNnbrdFEIA4OR2No5KHIdZrhG5s0j1MM5DhENzHmY9rvRcdSu3K6yCSalheAFm0r9hukHTyxpthGNZ796ZQKHAKWVLw5IlXdBfpP2rQqLH+fhEg81Pn/dG/ssH8QlaD9NCmo/hYgZqQS0navSuq6kq6tJWCtwIUzlzPApLONKkg3xa0rOawRENQPs=
    - AWS_DEFAULT_REGION=ap-southeast-2
    - INGEST_VERSION: $(lein pom &> /dev/null && 
                        mvn -q -Dexec.executable="echo" 
                               -Dexec.args='${project.version}' 
                               --non-recursive exec:exec)
    - INGEST_TAG: $(git describe --tags)

##############################################################################
# Desired workflow:
#
# Test:
# - All commits! (Add my cloned version as additional origin to secure online daily work).
#
# Publish:
# From master:
# - all commits with snapshot version (and no tag)
# - non-snapshots if they have a corresponding version tag
#
# From version branch:
# - commits with a corresponding version-patch# tag
#
##############################################################################

# Pipeline stages.
jobs:
  include:
  - stage: test
    #if: branch IN (master, devel) OR branch =~ ^version-
    script:
    - echo "I'm testing Ingestor "$INGEST_VERSION
  - stage: publish
    #if: env(INGEST_VERSION) =~ ^0.1.0-SNAPSHOT$
    script:
    - if [[ $INGEST_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+-SNAPSHOT$ ]] && 
         [[ ! $INGEST_TAG =~ ^stellar-ingest-[0-9]+\.[0-9]+\.[0-9]$ ]] ; then
        echo "I'm publishing Ingestor Version |"$INGEST_VERSION"| - Tag |"$INGEST_TAG"|";
      else
        echo "CONFLICT in publishing Ingestor Version |"$INGEST_VERSION"| - Tag |"$INGEST_TAG"|"; exit 1;
      fi
  - stage: release
    script:
    - if [[ $INGEST_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+-SNAPSHOT$ ]] && 
         [[ $INGEST_TAG = "stellar-ingest-$INGEST_VERSION" ]] ; then
        echo "I'm publishing Ingestor Version |"$INGEST_VERSION"| - Tag |"$INGEST_TAG"|";
      else
        echo "CONFLICT in publishing Ingestor Version |"$INGEST_VERSION"| - Tag |"$INGEST_TAG"|"; exit 1;
      fi

    # - echo "I'm publishing Ingestor |"$INGEST_VERSION"|"
    # - echo "And the tag is |"$TRAVIS_TAG"|"


# Snapshot deploy.
#gg="0.0.1-SNAPSHOT"; TRAVIS_TAG=""; if [[ $gg =~ ^[0-9]+\.[0-9]+\.[0-9]+-SNAPSHOT$ ]] && [[ $TRAVIS_TAG = "" ]] ; then echo $gg; else echo "no"; fi
#INGEST_VERSION="0.0.1-SNAPSHOT"; TRAVIS_TAG=""; if [[ $INGEST_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+-SNAPSHOT$ ]] && [[ $TRAVIS_TAG = "" ]] ; then echo "I'm publishing Ingestor: Version |"$INGEST_VERSION"| - Tag |"$TRAVIS_TAG"|"; else echo "CONFLICT in publishing Ingestor! Version |"$INGEST_VERSION"| - Tag |"$TRAVIS_TAG"|"; exit 1; fi
#INGEST_VERSION="0.0.1-SNAPSHOT"; TRAVIS_TAG=""; if [[ $INGEST_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+-SNAPSHOT$ ]] && [[ $TRAVIS_TAG = "" ]] ; then echo "I'm publishing Ingestor Version $INGEST_VERSION - Tag $TRAVIS_TAG"; else echo "CONFLICT in publishing Ingestor Version $INGEST_VERSION - Tag $TRAVIS_TAG"; exit 1; fi


