language: clojure
jdk: oraclejdk8

jobs:
  include:
    - stage: install
      script: lein deps
    - stage: compile
      script: lein compile
    - stage: test
      script: lein test
    - stage: publish
      script:
      - lein deploy
      - lein deploy-uberjar
