language: clojure
jdk:
  - oraclejdk8

# Environment variables (e.g. encrypted credentials).
# env:
#   global:
#   - var1
#   - var2

# env just tranlates to bash export... can we put a script?
# Setting environment variables from .travis.yml
# $ export INGEST_VERSION=0.1.0-SNAPSHOT
env:
  - INGEST_VERSION: $(lein pom &> /dev/null && mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)

# stages:
# - test
# - publish


##############################################################################
# Desired workflow:
#
# Test:
# - All commits! (Add my cloned version as additional origin to secure online daily work).
#
# Publish:
# From master:
# - all commits with snapshot version
# - non-snapshots if they have a corresponding version tag
#
# From version branch:
# - commits with a corresponding version-patch# tag
#
##############################################################################

# This section gets executed before the stages script sections.
# before_script:
# - export INGEST_VERSION=$(lein pom &> /dev/null && mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)    

# Pipeline stages.
jobs:
  include:
  # Vars defined in a stage are not available in the others.
  # - stage: prepare
  #   script:
  #   - export INGEST_VERSION=$(lein pom &> /dev/null && mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)    
  - stage: test
    #if: branch IN (master, devel) OR branch =~ ^version-
    script:
    - echo "I'm testing Ingestor "$INGEST_VERSION
  - stage: publish
    #if: env(INGEST_VERSION) =~ ^0.1.0-SNAPSHOT$
    script:
    - echo "I'm publishing Ingestor |"$INGEST_VERSION"|"
    - echo "And the tag is |"$TRAVIS_TAG"|"
