language: clojure
jdk:
  - oraclejdk8

env:
  - INGEST_VERSION: $(lein pom &> /dev/null && mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)

##############################################################################
# Desired workflow:
#
# Test:
# - All commits! (Add my cloned version as additional origin to secure online daily work).
#
# Publish:
# From master:
# - all commits with snapshot version (and no tag)
# - non-snapshots if they have a corresponding version tag
#
# From version branch:
# - commits with a corresponding version-patch# tag
#
##############################################################################

# Pipeline stages.
jobs:
  include:
  - stage: test
    #if: branch IN (master, devel) OR branch =~ ^version-
    script:
    - echo "I'm testing Ingestor "$INGEST_VERSION
  - stage: publish
    #if: env(INGEST_VERSION) =~ ^0.1.0-SNAPSHOT$
    script:
    # - if [[ $INGEST_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+-SNAPSHOT$ ]] && [[ $TRAVIS_TAG = "" ]] ; then echo "I'm publishing Ingestor Version |"$INGEST_VERSION"| - Tag |"$TRAVIS_TAG"|"; else echo "CONFLICT in publishing Ingestor Version |"$INGEST_VERSION"| - Tag |"$TRAVIS_TAG"|"; exit 1; fi
    - if [[ $INGEST_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+-SNAPSHOT$ ]] && [[ $TRAVIS_TAG = "" ]] ; then
        echo "I'm publishing Ingestor Version |"$INGEST_VERSION"| - Tag |"$TRAVIS_TAG"|";
      else
        echo "CONFLICT in publishing Ingestor Version |"$INGEST_VERSION"| - Tag |"$TRAVIS_TAG"|"; exit 1;
      fi

    # - echo "I'm publishing Ingestor |"$INGEST_VERSION"|"
    # - echo "And the tag is |"$TRAVIS_TAG"|"


# Snapshot deploy.
#gg="0.0.1-SNAPSHOT"; TRAVIS_TAG=""; if [[ $gg =~ ^[0-9]+\.[0-9]+\.[0-9]+-SNAPSHOT$ ]] && [[ $TRAVIS_TAG = "" ]] ; then echo $gg; else echo "no"; fi
#INGEST_VERSION="0.0.1-SNAPSHOT"; TRAVIS_TAG=""; if [[ $INGEST_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+-SNAPSHOT$ ]] && [[ $TRAVIS_TAG = "" ]] ; then echo "I'm publishing Ingestor: Version |"$INGEST_VERSION"| - Tag |"$TRAVIS_TAG"|"; else echo "CONFLICT in publishing Ingestor! Version |"$INGEST_VERSION"| - Tag |"$TRAVIS_TAG"|"; exit 1; fi
#INGEST_VERSION="0.0.1-SNAPSHOT"; TRAVIS_TAG=""; if [[ $INGEST_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+-SNAPSHOT$ ]] && [[ $TRAVIS_TAG = "" ]] ; then echo "I'm publishing Ingestor Version $INGEST_VERSION - Tag $TRAVIS_TAG"; else echo "CONFLICT in publishing Ingestor Version $INGEST_VERSION - Tag $TRAVIS_TAG"; exit 1; fi


